### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by beutlich** [ltx-simulation/ScalableTranslationStatistics#1]
There are two license files in the repo as of e3b3ae7b431fc40b4489761750fa1bffef0f9289. Whereas LICENSE is a standard BSD-3-clause license, the other file License.md is a non-standard BSD-3-clause license which seems to be copied from https://github.com/lbl-srg/modelica-buildings/blob/master/Buildings/legal.html as it points to Lawrence Berkeley National Laboratory in the added paragraph.

It would be very useful if only one license could be applied, preferably an OSI approved license. Thanks!

**Comment by MatthiasBSchaefer** [comment]
Clarification of License: Now, the non-standard BSD-3 clause license is valid for the ScalableTranslationStatistics Library.
