### ISSUE TITLE
Versioning and make a release

### ISSUE THREAD

**Issue by AnHeuermann** [ltx-simulation/ScalableTranslationStatistics#3]
Add the library version to [package.mo](https://github.com/ltx-simulation/ScalableTranslationStatistics/blob/main/package.mo#L32) and make a release on GitHub.

## Steps

  1. Add version tag `1.1.0` to package.mo
  2. Tag the commits for `v1.0.0` and `v1.1.0` on GitHub
  3. Publish a release on GitHub for each tagged version

**Comment by MatthiasBSchaefer** [comment]
- v.1.0.0 is not publically available 
- v.1.1.0 is published and tagged now
