### ISSUE TITLE
Error message in samples with scaled sparsity

### ISSUE THREAD

**Issue by koart81** [ltx-simulation/ScalableTranslationStatistics#6]
Error message appears in library samples with scaled sparsity (e.g. ScalableTranslationStatistics.Mechanics.Examples.Test_STS_Friction,  compiled simulation with Visual Studio as compiler in SimulationX) probably because the library is not consistent:

In Modelica is the function msleep is defined as following:
 input Real waitingTime "waiting time in mikroseconds";
 external "C" msleep(waitingTime) annotation(Include="#include <sleep_vs.c>", IncludeDirectory="modelica://ScalableTranslationStatistics/Resources");

In the file sleep_vs.c (and also other in sleep_gcc.c) is msleep with other parameters and other return type defined:
int msleep(int usec) ;

**Comment by koart81** [comment]
@MatthiasBSchaefer After commit 1d4411067de438bb99bc26e78d6168db785679d5 (
BugFix: DataType consistency for external sleeping routine)
the error appears in the model ScalableTranslationStatistics.Mechanics.Examples.Test_STS_Friction (as well as in all other sample models) before simulation:
.\cg_States_10.c
.\cg_States_10_init.c
.\cg_States_10_functions.c
.\cg_States_10_decl.c
.\cg_States_10_initjac.c
.\cg_States_10_jac.c
.\cg_States_10_tracing.c
.\ITI_AllocClockInference.c
.\ITI_ClockInference.c
In file included from .\cg_States_10_functions.c:14:
.\cg_States_10_functions.h:13:6: error: conflicting types for 'msleep'
   13 | void msleep(ITI_int /*waitingTime*/);
      |      ^~~~~~
In file included from .\cg_States_10_functions.c:9:
C:\Users\...\Resources/sleep_vs.c:3:5: note: previous definition of 'msleep' was here
    3 | int msleep(int usec) {
      |     ^~~~~~
makefile_tdmgcc:39: recipe for target '.\cg_States_10_functions.o' failed
mingw32-make: *** [.\cg_States_10_functions.o] Error 1
mingw32-make: *** Waiting for unfinished jobs....

States_10.dll - 1 Error(s), 0 Warning(s)

**Comment by MatthiasBSchaefer** [comment]
Hopefully the new commit 1d44110 fixes the problem.
The sleeping #c-routines don't have a return value anymore (void)
@koart81 can you please try in Simulation X ?

**Comment by koart81** [comment]
@MatthiasBSchaefer Now all samples with scaled sparsity are working in SimulationX as expected,  I will close this issue.
